ALTER TABLE CLASSIC1.STUDENT_HISTORY
MODIFY(STUDENT_ID  NOT NULL);


ALTER TABLE CLASSIC1.STUDENT_HISTORY
MODIFY(CLASS  NOT NULL);


ALTER TABLE CLASSIC1.STUDENT_HISTORY
MODIFY(BRANCH  NOT NULL);


ALTER TABLE CLASSIC1.STUDENT_HISTORY
MODIFY(SECTION  NOT NULL);


ALTER TABLE CLASSIC1.STUDENT_HISTORY
MODIFY(TYPE  NOT NULL);


ALTER TABLE CLASSIC1.STUDENT_HISTORY
 ADD (user_id  VARCHAR2(50)                         NOT NULL);

ALTER TABLE CLASSIC1.STUDENT_HISTORY
 ADD (status_id  VARCHAR2(10)                       NOT NULL   DEFAULT 'HOLD');

ALTER TABLE CLASSIC1.STUDENT_HISTORY
 ADD (remarks  VARCHAR2(100));

