ALTER TABLE CLASSIC.STUDENT_HISTORY
MODIFY(FEE  DEFAULT 0);

ALTER TABLE CLASSIC.STUDENT_HISTORY
MODIFY(DISCOUNT_PER  DEFAULT 0);

ALTER TABLE CLASSIC.STUDENT_HISTORY
MODIFY(DISCOUNT_AMOUNT  DEFAULT 0);

ALTER TABLE CLASSIC.STUDENT_HISTORY
 ADD (ARREARS  NUMBER                               DEFAULT 0);

