SELECT DISTINCT TO_CHAR(FEE_MONTH,'DD-MM-YYYY') FROM STU_FEE WHERE CLASS='I' AND FEE_MONTH = '01-MAR-23' ORDER BY FEE_MONTH DESC;


DELETE FROM STU_FEE_DET WHERE CHALLAN_ID IN (SELECT CHALLAN_ID FROM  STU_FEE WHERE CLASS='I' AND FEE_MONTH = '01-MAR-23');
DELETE FROM STU_FEE WHERE CHALLAN_ID IN (SELECT CHALLAN_ID FROM  STU_FEE WHERE CLASS='I' AND FEE_MONTH = '01-MAR-23');
DELETE FROM STU_MONTHLY_CHALLAN_NO WHERE CHALLAN_ID IN (SELECT CHALLAN_ID FROM  STU_FEE WHERE CLASS='I' AND FEE_MONTH = '01-MAR-23');