SELECT DISTINCT BRANCH FROM STU_HISTORY;
SELECT COUNT(*), BRANCH FROM STU_HISTORY GROUP BY BRANCH;
UPDATE STU_HISTORY SET BRANCH='SIALKOT CAMPUS' WHERE BRANCH='MAIN BRANCH';
ALTER TABLE ALLIED.STU_FEE  ADD (FINE  NUMBER);


select fee_month_id from stu_fee_months where fee_month_id >= add_months(sysdate,-3)