CREATE TABLE CLASSIC1.BRANCH_CLASS
(
  BRANCH_ID  VARCHAR2(100 BYTE),
  CLASS_ID   VARCHAR2(40 BYTE),
  USER_ID    VARCHAR2(20 BYTE)                  NOT NULL,
  FDATETIME  DATE                               NOT NULL,
  STATUS_ID  VARCHAR2(10 BYTE)                  NOT NULL,
  CONSTRAINT BRANCH_SEC_STS_CHK  CHECK       (STATUS_ID IN ('HOLD','RELEASE')),
  CONSTRAINT BRANCH_SECTION_PK   PRIMARY KEY (BRANCH_ID, CLASS_ID),
  CONSTRAINT BRANCH_SEC_USER_FK  FOREIGN KEY (USER_ID) 
 REFERENCES CLASSIC1.USERS (USER_ID));
