ALTER TABLE CLASSIC.STUDENT_HISTORY
MODIFY(FEE  NOT NULL);

ALTER TABLE CLASSIC.STUDENT_HISTORY
MODIFY(FEE  DEFAULT 0);

ALTER TABLE CLASSIC.STUDENT_HISTORY
MODIFY(DISCOUNT_PER  NOT NULL);

ALTER TABLE CLASSIC.STUDENT_HISTORY
MODIFY(DISCOUNT_PER  DEFAULT 0);

ALTER TABLE CLASSIC.STUDENT_HISTORY
MODIFY(DISCOUNT_AMOUNT  NOT NULL);

ALTER TABLE CLASSIC.STUDENT_HISTORY
MODIFY(DISCOUNT_AMOUNT  DEFAULT 0);

ALTER TABLE CLASSIC.STUDENT_HISTORY
 ADD (arrears  NUMBER(9)                            DEFAULT 0                     NOT NULL);

