ALTER TABLE FLEX.AC_YEAR DROP COLUMN INSERT_BY;
ALTER TABLE FLEX.AC_YEAR DROP COLUMN INSERT_DATE;
ALTER TABLE FLEX.AC_YEAR DROP COLUMN INSERT_TERM;
ALTER TABLE FLEX.AC_YEAR DROP COLUMN LAST_UPDATED_BY;
ALTER TABLE FLEX.AC_YEAR DROP COLUMN LAST_UPDATED_DATE;
ALTER TABLE FLEX.AC_YEAR DROP COLUMN LAST_UPDATED_TERM;

CREATE TABLE INV_TRANS_AZIZ
(
  TRANS_ID          NUMBER(8),
  TRANS_YEAR        VARCHAR2(5 BYTE),
  TRANS_DATE        DATE,
  TRANS_TYPE        VARCHAR2(10 BYTE),
  GIR_ID            NUMBER(6),
  GIR_YEAR          VARCHAR2(5 BYTE),
  GIR_DETAIL_ID     NUMBER(6),
  IR_ID             NUMBER(7),
  IR_YEAR           VARCHAR2(5 BYTE),
  IR_DETAIL_ID      NUMBER(7),
  ISSUE_QTY         NUMBER(20,6),
  ISSUE_VALUE       NUMBER(20,6),
  REC_QTY           NUMBER(20,6),
  REC_VALUE         NUMBER(20,6),
  REMARKS           VARCHAR2(120 BYTE),
  DEPARTMENT_ID     VARCHAR2(30 BYTE),
  STATUS_ID         NUMBER(2),
  FDATETIME         DATE,
  OPENING_QTY       NUMBER,
  OPENING_VALUE     NUMBER,
  AVG_RATE          NUMBER,
  FRR_ID            NUMBER(6),
  FRR_YEAR          VARCHAR2(5 BYTE),
  FRR_DETAIL_ID     NUMBER(3),
  FGRR_ID           NUMBER(5),
  FGRR_YEAR         VARCHAR2(5 BYTE),
  CLOSING_QTY       NUMBER(15,6),
  CLOSING_VALUE     NUMBER(15,6),
  ITEM_DESCRIPTION  VARCHAR2(400 BYTE),
  SC_FINISH_ID      VARCHAR2(50 BYTE)           DEFAULT '0',
  OUR_CPO           VARCHAR2(20 BYTE),
  CPO_YEAR          VARCHAR2(5 BYTE),
  USER_ID           VARCHAR2(20 BYTE)           DEFAULT NULL,
  COUNTER           NUMBER,
  SC_ID             NUMBER(10),
  SAN_ID            NUMBER(10),
  SAN_YEAR          VARCHAR2(5 BYTE),
  BTN_ID            NUMBER,
  BTN_YEAR          VARCHAR2(5 BYTE),
  ITEM_STATUS       VARCHAR2(10 BYTE),
  ECR_ID            NUMBER,
  ECR_DETAIL_ID     NUMBER
)
TABLESPACE oracubes
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
------
CREATE TABLE INV_TRIAL_TEMP
(
  SC_ID             NUMBER(6),
  OPENING_QTY       NUMBER,
  OPENING_VALUE     NUMBER,
  REC_QTY           NUMBER,
  REC_VALUE         NUMBER,
  ISSUE_QTY         NUMBER,
  ISSUE_VALUE       NUMBER,
  UOM_ID            VARCHAR2(25 BYTE),
  ITEM_DESCRIPTION  VARCHAR2(300 BYTE),
  CLOSING_QTY       NUMBER,
  CLOSING_VALUE     NUMBER
)
TABLESPACE oracubes
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          192K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;