alter TABLE AC_SETUP
add (
  FBANK_CHARGES_COA_MAIN_ID  NUMBER(2),
  FBANK_CHARGES_COA_SUB_ID   NUMBER(4),
  FBANK_CHARGES_COA_ID       NUMBER(6),
  LBANK_CHARGES_COA_MAIN_ID  NUMBER(2),
  LBANK_CHARGES_COA_SUB_ID   NUMBER(4),
  LBANK_CHARGES_COA_ID       NUMBER(6),
  EDS_COA_MAIN_ID            NUMBER(2),
  EDS_COA_SUB_ID             NUMBER(4),
  EDS_COA_ID                 NUMBER(6),
  WH_TAX_COA_MAIN_ID         NUMBER(2),
  WH_TAX_COA_SUB_ID          NUMBER(4),
  WH_TAX_COA_ID              NUMBER(6),
  OTHER_EXP_COA_MAIN_ID      NUMBER(2),
  OTHER_EXP_COA_SUB_ID       NUMBER(4),
  OTHER_EXP_COA_ID           NUMBER(6)
)


