ALTER TABLE ASKARI.BARCODE_ATTENDANCE
 ADD (SHIFT_IN_TIME  VARCHAR2(5));

ALTER TABLE ASKARI.BARCODE_ATTENDANCE
 ADD (SHIFT_OUT_TIME  VARCHAR2(5));

ALTER TABLE ASKARI.BARCODE_ATTENDANCE
 ADD (SHIFT_REST_DAY  VARCHAR2(20));

