ALTER TABLE ASKARI1.COMPANY_SETUP
 ADD (RECEIVING_AJV  VARCHAR2(3)                    DEFAULT 'YES');

ALTER TABLE ASKARI1.COMPANY_SETUP
 ADD (ISSUANCE_AJV  VARCHAR2(3)                     DEFAULT 'YES');

