ALTER TABLE ASKARI.EMPLOYEE
 ADD (place_of_birth  VARCHAR2(20));

ALTER TABLE ASKARI.EMPLOYEE
 ADD (father_hus_occupation  VARCHAR2(30));

ALTER TABLE ASKARI.EMPLOYEE
 ADD (temp_address  VARCHAR2(200));

ALTER TABLE ASKARI.EMPLOYEE
 ADD (emergency_contact_no  VARCHAR2(20));

