ALTER TABLE ASKARI.JCD
 ADD CONSTRAINT JCD_SUPPLIER_FK 
 FOREIGN KEY (SUPPLIER_ID) 
 REFERENCES ASKARI.SUPPLIER (SUPPLIER_ID);

ALTER TABLE ASKARI.JCD
 ADD CONSTRAINT JCD_USER_FK 
 FOREIGN KEY (USER_ID) 
 REFERENCES ASKARI.USERS (USER_ID);

ALTER TABLE ASKARI.JCD
 ADD CONSTRAINT JCD_ISSUE_USER_FK 
 FOREIGN KEY (ISSUE_USER_ID) 
 REFERENCES ASKARI.USERS (USER_ID);

ALTER TABLE ASKARI.JCD
 ADD CONSTRAINT JCD_REC_USER_FK 
 FOREIGN KEY (REC_USER_ID) 
 REFERENCES ASKARI.USERS (USER_ID);

