CREATE OR REPLACE VIEW ORACLE.MPD_VIEW
(MP_ID, STORE_CODE, SC_MAIN_ID, SC_MAIN_DESC, SC_DESC, 
 VARIABLE, RSIZE, QTY, UNIT_ID, MAIN_PART, 
 SUB_PART)
AS 
SELECT MP_ID, STORE_CODE, M.SC_MAIN_ID, SC_MAIN_DESC, SC_DESC, VARIABLE, RSIZE, QTY, s.unit_id, main_part, sub_part
FROM SC_VIEW S,
MPD M
WHERE M.SC_MAIN_ID = S.SC_MAIN_ID
AND M.SC_SUB_ID = S.SC_SUB_ID
AND M.SC_ID = S.SC_ID;

