ALTER TABLE ASKARI.OGP_DETAIL DROP COLUMN INSERT_BY;

ALTER TABLE ASKARI.OGP_DETAIL DROP COLUMN INSERT_DATE;

ALTER TABLE ASKARI.OGP_DETAIL DROP COLUMN INSERT_TERM;

ALTER TABLE ASKARI.OGP_DETAIL DROP COLUMN LAST_UPDATED_BY;

ALTER TABLE ASKARI.OGP_DETAIL DROP COLUMN LAST_UPDATED_DATE;

ALTER TABLE ASKARI.OGP_DETAIL DROP COLUMN LAST_UPDATED_TERM;

