ALTER TABLE ORACLE4.PO_DELETED
 ADD (Deleted_user  VARCHAR2(20));

ALTER TABLE ORACLE4.PO_DELETED
 ADD (Deleted_fdatetime  DATE);

ALTER TABLE ORACLE4.PO_DELETED
 ADD (Deleted_reason  VARCHAR2(100));

