ALTER TABLE ASKARI.WO
 ADD (OUR_CPO  NUMBER);

ALTER TABLE ASKARI.WO
 ADD (CPO_YEAR  VARCHAR2(5));

ALTER TABLE ASKARI.WO
 ADD (CPO_ID  VARCHAR2(25));

ALTER TABLE ASKARI.WO
 ADD (STYLE  VARCHAR2(50));

ALTER TABLE ASKARI.WO
 ADD (COLOR_ID  VARCHAR2(50));

