/*
DECLARE
  CURSOR CURIR IS SELECT * FROM INV_IR;
BEGIN
  FOR R IN CURIR
  LOOP 
    UPDATE AC_VOUCHER SET IR_ID = R.IR_ID WHERE VOUCHER_SEQ = R.VOUCHER_SEQ;
    --NULL;
  END LOOP;
END; 

DROP TABLE SGS1.INV_PROBLEM CASCADE CONSTRAINTS;

CREATE TABLE SGS1.INV_PROBLEM
(
  INV_PROBLEM_ID  NUMBER,
  DOC             VARCHAR2(20 BYTE),
  DOC_ID          NUMBER,
  DESCRIPTION     VARCHAR2(300 BYTE),
  FDATETIME       DATE
)
TABLESPACE ORACUBES
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING; 

CREATE OR REPLACE FUNCTION SGS1.inv_ir_trx_verify (i NUMBER)
   RETURN VARCHAR2
IS
   x    NUMBER;
   iq   NUMBER;
   rq   NUMBER;
   rt   NUMBER;
   it   NUMBER;
BEGIN
   SELECT SUM (issue_qty), SUM (rec_qty)
     INTO iq, rq
     FROM inv_ir_detail
    WHERE ir_id = i;

   SELECT SUM (issue_qty), SUM (rec_qty)
     INTO it, rt
     FROM inv_trans
    WHERE mis_ref = 'SALE#' || i;

   --AZIZ.MSG(IQ||'='||IT||' '||RQ||'='||RT);
   IF (iq <> it) or (rq <> rt)
   THEN
---        UPDATE INV_IR SET AUDITED = 'OK' WHERE IR_ID = I;
   --- ELSE
      RETURN 'NO';
   END IF;

   RETURN 'OK';
END;
*/

DELETE FROM AC_VOUCHER_DETAIL WHERE VOUCHER_SEQ IN (SELECT VOUCHER_SEQ FROM AC_VOUCHER WHERE VOUCHER_SUB_TYPE_ID = 'CR-AJV' AND IR_ID IS NULL);
DELETE FROM AC_VOUCHER WHERE VOUCHER_SEQ IN (SELECT VOUCHER_SEQ FROM AC_VOUCHER WHERE VOUCHER_SUB_TYPE_ID = 'CR-AJV' AND IR_ID IS NULL);
SELECT COUNT(*) FROM AC_VOUCHER WHERE VOUCHER_SUB_TYPE_ID = 'CR-AJV' AND IR_ID IS NOT NULL;
CREATE SEQUENCE SGS1.INV_PROBLEM_SEQ;
create table inv_problem (inv_problem_id number, doc varchar2(20), doc_id number, description varchar2(300));

ALTER TABLE SGS1.AC_VOUCHER ADD CONSTRAINT AC_VOUCHER_SR_AJV_CHK CHECK ((VOUCHER_SUB_TYPE_ID = 'CR-AJV') OR (VOUCHER_SUB_TYPE_ID <> 'CR-AJV';);

SELECT MIS_REF, TRANS_DATE, COUNT(*) FROM INV_TRANS WHERE MIS_REF IS NOT NULL AND SUBSTR(MIS_REF,0,3) <> 'IGP' GROUP BY MIS_REF, TRANS_DATE
HAVING COUNT(*) > 2
ORDER BY COUNT(*) DESC;

SELECT SUM(ISSUE_QTY), SUM(REC_QTY) FROM INV_IR_DETAIL WHERE IR_ID = :XYZ;
SELECT SUM(ISSUE_QTY), SUM(REC_QTY) FROM INV_TRANS WHERE MIS_REF='SALE#'||:XYZ;


