ALTER TABLE ASKARI2.BANK_ACCOUNT
 ADD (wh_coa_main_id  NUMBER(6));

ALTER TABLE ASKARI2.BANK_ACCOUNT
 ADD (wh_coa_sub_id  NUMBER(4));

ALTER TABLE ASKARI2.BANK_ACCOUNT
 ADD (wh_coa_id  NUMBER(2));

