ALTER TABLE CMI1.AC_VOUCHER
 ADD CONSTRAINT AC_VOC_IR_UQ
 UNIQUE (IR_ID, IR_YEAR);
 
 SELECT VOUCHER_SEQ , IR_ID, IR_YEAR FROM AC_VOUCHER 
 WHERE IR_ID||'-'||IR_YEAR IN (SELECT IR_ID||'-'||IR_YEAR FROM AC_VOUCHER
 WHERE IR_ID IS NOT NULL
 GROUP BY IR_ID, IR_YEAR
 HAVING COUNT(*) > 1)
 ORDER BY IR_ID, IR_YEAR;
 _
