ALTER TABLE ORACLE.CPO_DETAIL
 ADD (PROD_GOAHEAD_DATETIME  DATE);

ALTER TABLE ORACLE.CPO_DETAIL
 ADD (CLOSING_DATETIME  DATE);

ALTER TABLE ORACLE.CPO_DETAIL
 ADD (CLOSED_BY  VARCHAR2(20));

