ALTER TABLE ASKARI.EMPLOYEE_SHIFT
 ADD (hr_shift_id  VARCHAR2(50));

ALTER TABLE ASKARI.EMPLOYEE_SHIFT DROP COLUMN IN_TIME;

ALTER TABLE ASKARI.EMPLOYEE_SHIFT DROP COLUMN OUT_TIME;

ALTER TABLE ASKARI.EMPLOYEE_SHIFT DROP COLUMN REST_DAY;

