ALTER TABLE GILLANI.HR_EMPLOYEE  ADD (salary_adv_coa_seq  NUMBER);
ALTER TABLE GILLANI.HR_EMPLOYEE  ADD (loan_coa_seq  NUMBER);
ALTER TABLE GILLANI.HR_EMPLOYEE  ADD (salary_coa_seq  NUMBER);
ALTER TABLE GILLANI.HR_EMPLOYEE  ADD (salary_payable_coa_seq  NUMBER);
