ALTER TABLE ORACLE.MPD
 DROP PRIMARY KEY CASCADE;

ALTER TABLE ORACLE.MPD
 ADD CONSTRAINT mpd_pk
 PRIMARY KEY
 (MP_ID, CUSTOMER_ID, MAIN_PART, SUB_PART, SC_MAIN_ID, SC_SUB_ID, SC_ID, RSIZE);

