ALTER TABLE CMI1.EXP_SAMPLE_ISU_REC
 DROP PRIMARY KEY CASCADE;
DROP TABLE CMI1.EXP_SAMPLE_ISU_REC CASCADE CONSTRAINTS;

CREATE TABLE CMI1.EXP_SAMPLE_ISU_REC
(
  SAMPLE_ID          NUMBER,
  DESCRIPTION        VARCHAR2(100 BYTE)         NOT NULL,
  ISSUED_BY          VARCHAR2(100 BYTE)         NOT NULL,
  ISSUE_DATETIME     DATE                       NOT NULL,
  ISSUE_TO           VARCHAR2(100 BYTE)         NOT NULL,
  RECEIVED_BY        VARCHAR2(100 BYTE),
  RECEIVED_DATETIME  DATE
)
TABLESPACE ORACUBES
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CMI1.EXP_SAMPLE_ISU_REC_PK ON CMI1.EXP_SAMPLE_ISU_REC
(SAMPLE_ID)
LOGGING
TABLESPACE ORACUBES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CMI1.EXP_SAMPLE_ISU_REC ADD (
  CONSTRAINT EXP_SAMPLE_ISU_REC_PK
 PRIMARY KEY
 (SAMPLE_ID)
    USING INDEX 
    TABLESPACE ORACUBES
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

