CREATE TABLE ASKARI.TASK
(
  TASK_ID      VARCHAR2(50),
  USER_ID      VARCHAR2(20),
  FDATETIME    DATE,
  DESCRIPTION  VARCHAR2(100),
  DEPARTMENT   VARCHAR2(100)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE ASKARI.TASK ADD (
  CONSTRAINT task_pk
 PRIMARY KEY
 (TASK_ID));

ALTER TABLE ASKARI.TASK ADD (
  CONSTRAINT task_user_fk 
 FOREIGN KEY (USER_ID) 
 REFERENCES ASKARI.USERS (USER_ID));

