SELECT SUBSTR(CUSTOMER, 0, 25) CUSTOMER, L5 L5, SUM(ROUND(AMOUNT)) AMT FROM INV_IR_DETAIL_VIEW GROUP BY SUBSTR(CUSTOMER, 0, 25), L5;

SELECT DISTINCT L5 FROM INV_SC ORDER BY L5;
UPDATE INV_SC SET L5='RECKWEG' WHERE L5=' RECKEWEG';
UPDATE INV_SC SET L5='RECKWEG' WHERE L5='RECKEWEG';
UPDATE INV_SC SET L5='KALKUR' WHERE L5='KALKURENAL';
UPDATE INV_SC SET L5='BHARGVA' WHERE L5='BHARGAVA';
UPDATE INV_SC SET L5='CONTIMD' WHERE L5='CONTIMADE';
UPDATE INV_SC SET L5='HERBAMD' WHERE L5='HERBAMED';
UPDATE INV_SC SET L5='MYHELTH' WHERE L5='MY HEALTH';
UPDATE INV_SC SET L5='360' WHERE L5=' 360';