ALTER TABLE ADDOS.EXP_CPO_DETAIL  ADD (hsk_code  VARCHAR2(50));
ALTER TABLE ADDOS.EXP_CPO_DETAIL  ADD (customs_rate  NUMBER(5,2));
ALTER TABLE ADDOS.EXP_CSC ADD (hsk_code  VARCHAR2(50));
ALTER TABLE ADDOS.EXP_CSC ADD (customs_rate  NUMBER(5,2));

