ALTER TABLE ADDOS.EXP_PACKING_DETAIL
 ADD CONSTRAINT packing_det_cpo_fk 
 FOREIGN KEY (CPO_ID) 
 REFERENCES ENIKA.EXP_CPO (CPO_ID);
 
 ALTER TABLE ADDOS.EXP_CPO_DETAIL
 ADD CONSTRAINT cpo_det_pk
 PRIMARY KEY
 (CPO_ID, POSITION);


ALTER TABLE ADDOS.EXP_PACKING_DETAIL
 ADD CONSTRAINT packing_det_cpo_det_fk 
 FOREIGN KEY (CPO_ID, POSITION) 
 REFERENCES ADDOS.EXP_CPO_DETAIL (CPO_ID, POSITION);
 
 ALTER TABLE ADDOS.PROD_JCD
 DROP CONSTRAINT JCD_CPO_DET_PK;
 
 ---ALTER TABLE ADDOS.EXP_CPO  DROP CONSTRAINT CPO_CPO_YR_UQ;

ALTER TABLE ADDOS.EXP_CPO  ADD CONSTRAINT cpo_our_cpo_uq UNIQUE (OUR_CPO);

select jcd_id, our_cpo from prod_jcd where our_cpo not in (select our_cpo from exp_cpo);
delete from prod_jcd where our_cpo not in (select our_cpo from exp_cpo);



ALTER TABLE ADDOS.PROD_JCD
 ADD CONSTRAINT prod_jcd_cpo_fk 
 FOREIGN KEY (OUR_CPO) 
 REFERENCES ADDOS.EXP_CPO (OUR_CPO);

EXP_PACKING_VIEW
