CREATE OR REPLACE VIEW STU_USER_RAW_STU_FEEDING_VIEW
AS
SELECT USER_ID, TRUNC(FDATETIME) FDATETIME, COUNT(*) ENTRIES FROM STU_STUDENT GROUP BY USER_ID, TRUNC(FDATETIME);

CREATE OR REPLACE VIEW STU_USER_RAW_FEEDING_VIEW0
AS
SELECT TRUNC(FDATETIME) FDATETIME FROM STU_STUDENT GROUP BY TRUNC(FDATETIME)