--------------------------------------------------------
--  File created - Friday-May-13-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EXP_BANK_PI
--------------------------------------------------------

  CREATE TABLE "ADDOS"."EXP_BANK_PI" 
   (	"INV_PAYMENT_ID" NUMBER, 
	"PI_NO" NUMBER, 
	"CUSTOMER_ID" VARCHAR2(100 BYTE), 
	"PI_DATE" DATE, 
	"SHIP_TO" VARCHAR2(200 BYTE), 
	"MO" VARCHAR2(20 BYTE), 
	"CPO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EXP_BANK_PI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADDOS"."EXP_BANK_PI_PK" ON "ADDOS"."EXP_BANK_PI" ("INV_PAYMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EXP_BANK_PI_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADDOS"."EXP_BANK_PI_UK1" ON "ADDOS"."EXP_BANK_PI" ("PI_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EXP_BANK_PI
--------------------------------------------------------

  ALTER TABLE "ADDOS"."EXP_BANK_PI" ADD CONSTRAINT "EXP_BANK_PI_PK" PRIMARY KEY ("INV_PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADDOS"."EXP_BANK_PI" ADD CONSTRAINT "EXP_BANK_PI_UK1" UNIQUE ("PI_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADDOS"."EXP_BANK_PI" MODIFY ("INV_PAYMENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ADDOS"."EXP_BANK_PI" MODIFY ("PI_NO" NOT NULL ENABLE);
 
  ALTER TABLE "ADDOS"."EXP_BANK_PI" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ADDOS"."EXP_BANK_PI" MODIFY ("PI_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ADDOS"."EXP_BANK_PI" MODIFY ("SHIP_TO" NOT NULL ENABLE);
