--------------------------------------------------------
--  File created - Friday-May-13-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EXP_BANK_PI_DET
--------------------------------------------------------

  CREATE TABLE "ADDOS"."EXP_BANK_PI_DET" 
   (	"INV_PAYMENT_ID" NUMBER, 
	"QTY" NUMBER, 
	"STYLE" VARCHAR2(100 BYTE), 
	"COLOR" VARCHAR2(100 BYTE), 
	"ITEM_SIZE" VARCHAR2(20 BYTE), 
	"ITEM_DESC" VARCHAR2(200 BYTE), 
	"PRICE" NUMBER, 
	"UOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EXP_BANK_PI_DET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADDOS"."EXP_BANK_PI_DET_PK" ON "ADDOS"."EXP_BANK_PI_DET" ("INV_PAYMENT_ID", "STYLE", "COLOR", "ITEM_SIZE", "ITEM_DESC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EXP_BANK_PI_DET
--------------------------------------------------------

  ALTER TABLE "ADDOS"."EXP_BANK_PI_DET" ADD CONSTRAINT "EXP_BANK_PI_DET_PK" PRIMARY KEY ("INV_PAYMENT_ID", "STYLE", "COLOR", "ITEM_SIZE", "ITEM_DESC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADDOS"."EXP_BANK_PI_DET" MODIFY ("INV_PAYMENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ADDOS"."EXP_BANK_PI_DET" MODIFY ("STYLE" NOT NULL ENABLE);
 
  ALTER TABLE "ADDOS"."EXP_BANK_PI_DET" MODIFY ("COLOR" NOT NULL ENABLE);
 
  ALTER TABLE "ADDOS"."EXP_BANK_PI_DET" MODIFY ("ITEM_SIZE" NOT NULL ENABLE);
 
  ALTER TABLE "ADDOS"."EXP_BANK_PI_DET" MODIFY ("ITEM_DESC" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EXP_BANK_PI_DET
--------------------------------------------------------

  ALTER TABLE "ADDOS"."EXP_BANK_PI_DET" ADD CONSTRAINT "EXP_BANK_PI_DET_FK1" FOREIGN KEY ("INV_PAYMENT_ID")
	  REFERENCES "ADDOS"."EXP_BANK_PI" ("INV_PAYMENT_ID") ENABLE;
