ALTER TABLE ASKARI.CREDITOR_BALANCES
 ADD (cheque_no  VARCHAR2(30));

ALTER TABLE ASKARI.CREDITOR_BALANCES
 ADD (last_bills  NUMBER);

ALTER TABLE ASKARI.CREDITOR_BALANCES
 ADD (pdc_amount  NUMBER);

