CREATE OR REPLACE FUNCTION ADDOS.hr_cal_ot(e number, m date) RETURN NUMBER IS
X NUMBER;
BEGIN
    SELECT MIN_TO_HOUR(SUM(NUMBER_TO_MIN(NVL(OT_HOURS,0)))) INTO X FROM hr_ATTENDANCE WHERE EMPLOYEE_ID=E AND TRUNC(ATTENDANCE_DATE, 'MON')=M;
  RETURN X;
END;
/
