ALTER TABLE ASKARI.JCD
MODIFY(STAGE  NOT NULL);


ALTER TABLE ASKARI.JCD
MODIFY(EMPLOYEE_ID  NOT NULL);


ALTER TABLE ASKARI.JCD
MODIFY(ISSUE_DATE  NOT NULL);


ALTER TABLE ASKARI.JCD
MODIFY(QTY  NOT NULL);


ALTER TABLE ASKARI.JCD
MODIFY(ISSUE_USER_ID  NOT NULL);


ALTER TABLE ASKARI.JCD
MODIFY(OUR_CPO  NOT NULL);


ALTER TABLE ASKARI.JCD
MODIFY(CPO_YEAR  NOT NULL);


ALTER TABLE ASKARI.JCD
MODIFY(POSITION  NOT NULL);


ALTER TABLE ASKARI.JCD
MODIFY(OPERATION_TYPE  NOT NULL);


ALTER TABLE ASKARI.JCD
 ADD (PAID  VARCHAR2(3)                             NOT NULL);

ALTER TABLE ASKARI.JCD
 ADD (INHOUSE  VARCHAR2(3)                          NOT NULL);

ALTER TABLE ASKARI.JCD
 ADD (SUPPLIER_ID  NUMBER(4));

ALTER TABLE ASKARI.JCD
 ADD (USER_ID  VARCHAR2(20)                         NOT NULL);

ALTER TABLE ASKARI.JCD
 ADD (FDATETIME  DATE                               NOT NULL);

