ALTER TABLE LOAN  ADD (loan_type  VARCHAR2(15));
ALTER TABLE LOAN  ADD CONSTRAINT loan_type_chk  CHECK (loan_type in ('FIXED','DEDUCTABLE'));
ALTER TABLE LOAN ADD CONSTRAINT LOAN_STATUS_CHECK  CHECK (STATUS_ID IN ('HOLD','RELEASE'));/
/
