ALTER TABLE ORACLE4.OGP
 ADD (pr_id  NUMBER);

ALTER TABLE ORACLE4.OGP
 ADD (pr_year  VARCHAR2(2));

ALTER TABLE ORACLE4.OGP
 ADD CONSTRAINT ogp_pr_fk 
 FOREIGN KEY (pr_id, pr_year) 
 REFERENCES ORACLE4.PR (pr_id, pr_year);

