ALTER TABLE ASKARI.OGP_DETAIL
 ADD (sc_main_id  NUMBER(4));

ALTER TABLE ASKARI.OGP_DETAIL
 ADD (sc_sub_id  NUMBER(4));

ALTER TABLE ASKARI.OGP_DETAIL
 ADD (sc_id  NUMBER(4));

ALTER TABLE ASKARI.OGP_DETAIL
 ADD (in_out  VARCHAR2(3));

