ALTER TABLE ASKARI.SUPPLIER
MODIFY(EMPLOYEE_ID  NULL);


ALTER TABLE ASKARI.SUPPLIER
 ADD (user_id  VARCHAR2(20)                         DEFAULT aziz                  NOT NULL);

ALTER TABLE ASKARI.SUPPLIER
 ADD FOREIGN KEY (user_id) 
 REFERENCES ASKARI.USERS (user_id);

