ALTER TABLE ADDOS.AC_VOUCHER  ADD (packing_id  NUMBER(10));
rename inv_payemnt to exp_payment
view exp_inv_payment_view
view exp_packing_view
ALTER TABLE ADDOS.EXP_PAYMENT MODIFY(PACKING_YEAR  NULL);
ALTER TABLE ADDOS.EXP_PAYMENT MODIFY(CUSTOMER_ID  NULL);
ALTER TABLE ADDOS.AC_BANK_ACCOUNT  ADD (exp_wh_seq  NUMBER);
ALTER TABLE ADDOS.AC_BANK_ACCOUNT DROP COLUMN COA_MAIN_ID;
ALTER TABLE ADDOS.AC_BANK_ACCOUNT DROP COLUMN COA_SUB_ID;
ALTER TABLE ADDOS.AC_BANK_ACCOUNT DROP COLUMN COA_ID;
ALTER TABLE ADDOS.AC_BANK_ACCOUNT DROP COLUMN WH_COA_MAIN_ID;
ALTER TABLE ADDOS.AC_BANK_ACCOUNT DROP COLUMN WH_COA_SUB_ID;
ALTER TABLE ADDOS.AC_BANK_ACCOUNT DROP COLUMN WH_COA_ID;



