ALTER TABLE ADDOS.AC_VOUCHER_TYPE_DETAIL ADD (user_role  VARCHAR2(10));
DELETE FROM AC_VOUCHER_DETAIL WHERE VOUCHER_SEQ NOT IN (SELECT VOUCHER_SEQ FROM AC_VOUCHER);
ALTER TABLE ADDOS.AC_VOUCHER_DETAIL  ADD CONSTRAINT AC_VOUCHER_DET_VOUCHER_SEQ_FK  FOREIGN KEY (VOUCHER_SEQ)  REFERENCES ADDOS.AC_VOUCHER (VOUCHER_SEQ);
