ALTER TABLE ADDOS.EXP_CSC  ADD (pantone  VARCHAR2(50));
ALTER TABLE ADDOS.EXP_CSC  ADD (CANDEL  VARCHAR2(50));
ALTER TABLE ADDOS.EXP_CSC  ADD (PLOTTER  VARCHAR2(50));
ALTER TABLE ADDOS.EXP_CSC  ADD (INK  VARCHAR2(50));
ALTER TABLE ADDOS.EXP_CSC  ADD (PROFILE  VARCHAR2(50));
ALTER TABLE ADDOS.EXP_CSC  ADD (RECEIPE  VARCHAR2(50));
ALTER TABLE ADDOS.EXP_CSC ADD (COLOR_BOOK_REF  VARCHAR2(50));
exp_packing_view;
