SELECT DESCRIPTION, BUTTON_NAME, LABEL, TYPE FROM ADM_FRM_RPT_ACCESS_DET;
DROP TABLE ADM_FRM_RPT_ACCESS_DETAIL;

CREATE TABLE ADM_FRM_ACCESS_DETAIL
AS
SELECT DESCRIPTION, BUTTON_NAME, LABEL, TYPE FROM ADM_FRM_RPT_ACCESS_DET GROUP BY DESCRIPTION, BUTTON_NAME, LABEL, TYPE;

ALTER TABLE ADDOS.ADM_FRM_RPT_ACCESS_DETAIL  ADD CONSTRAINT ADM_FRM_RPT_ACCESS_DETAIL_PK  PRIMARY KEY  (DESCRIPTION, BUTTON_NAME);

ALTER TABLE ADDOS.ADM_FRM_RPT_ACCESS_DET
 DROP CONSTRAINT FRM_REP_ACS_DET_FK1;

ALTER TABLE ADDOS.ADM_FRM_RPT_ACCESS_DET
 ADD CONSTRAINT ADM_FRM_RPT_ACCESS_DET_FK 
 FOREIGN KEY (DESCRIPTION, BUTTON_NAME, TYPE) 
 REFERENCES ADDOS.ADM_FRM_RPT_ACCESS_DETAIL (DESCRIPTION, BUTTON_NAME, TYPE);

