ALTER TABLE ASKARI1.COMPANY_SETUP
 ADD (EMPLOYEE_SAL_AJV  VARCHAR2(3)                 DEFAULT 'YES');

ALTER TABLE ASKARI1.COMPANY_SETUP
 ADD (CONTRACTOR_WAGES_AJV  VARCHAR2(3)             DEFAULT 'YES');

