ALTER TABLE ORACLE.JCD
 ADD (OUR_CPO  VARCHAR2(5));

ALTER TABLE ORACLE.JCD
 ADD (CPO_YEAR  VARCHAR2(5));

ALTER TABLE ORACLE.JCD
 ADD (POSITION  NUMBER(3));

ALTER TABLE ORACLE.JCD
 ADD CONSTRAINT JCD_CPO_DET_PK 
 FOREIGN KEY (OUR_CPO, CPO_YEAR, POSITION) 
 REFERENCES ORACLE.CPO_DETAIL (OUR_CPO, CPO_YEAR, POSITION);

