select v.JCD_ID, v.EMPLOYEE_ID,  v.NAME, v.CPO_ID,  v.STYLE, v.COLOR_ID, v.RSIZE, 
       v.STAGE, v.STAGE_NAME, v.OPERATION_NO, v.OPERATION_ID, 
       v.ISSUE_DATE, v.ISSUE_QTY, v.ISSUE_STATUS_ID, v.REC_DATE, v.REC_QTY, OPERATION_RATE,  v.REC_QTY * OPERATION_RATE Amount,
        v.PAYMENT_STATUS_ID,v.PAYMENT_DATE
from prod_jcd_view v