ALTER TABLE LOAN
MODIFY(STATUS_ID VARCHAR2(10));
ALTER TABLE LOAN DROP COLUMN EMPLOYEE_ID;
ALTER TABLE LOAN DROP COLUMN INSERT_BY;
ALTER TABLE LOAN DROP COLUMN INSERT_DATE;
ALTER TABLE LOAN DROP COLUMN INSERT_TERM;
ALTER TABLE LOAN DROP COLUMN LAST_UPDATED_BY;
ALTER TABLE LOAN DROP COLUMN LAST_UPDATED_DATE;
ALTER TABLE LOAN DROP COLUMN LAST_UPDATED_TERM;
ED
/
