ALTER TABLE ASKARI.OGP
 ADD (IGP_ID  NUMBER(4));

ALTER TABLE ASKARI.OGP
 ADD (IGP_YEAR  VARCHAR2(5));

ALTER TABLE ASKARI.OGP
 ADD CONSTRAINT OGP_IGP_UQ
 UNIQUE (IGP_ID, IGP_YEAR);

ALTER TABLE ASKARI.OGP
 ADD CONSTRAINT OGP_IGP_FK 
 FOREIGN KEY (IGP_ID, IGP_YEAR) 
 REFERENCES ASKARI.IGP (IGP_ID, IGP_YEAR);

