CREATE TABLE SAL_CONT
(
  SAL_CONT_ID  DATE,
  FDATETIME    DATE                             DEFAULT sysdate               NOT NULL,
  STATUS_ID    VARCHAR2(10 BYTE)                NOT NULL,
  USER_ID      VARCHAR2(20 BYTE)                NOT NULL,
  CONSTRAINT SAL_CONT_STS_CHK CHECK (status_id  in ('HOLD','RELEASE','CANCEL')),
  CONSTRAINT SAL_CONT_PK PRIMARY KEY (SAL_CONT_ID),
  CONSTRAINT SAL_CONT_USER_FK  FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);