ALTER TABLE ASKARI.SALARY_ADVANCE
 ADD (VOUCHER_SEQ  NUMBER(9));

ALTER TABLE ASKARI.SALARY_ADVANCE
 ADD CONSTRAINT SAL_ADV_VSEQ_FK 
 FOREIGN KEY (VOUCHER_SEQ) 
 REFERENCES ASKARI.VOUCHER (VOUCHER_SEQ);

