ALTER TABLE ASKARI.SAL_CONT_DETAIL
 ADD CONSTRAINT SAL_CONT_DET_AJV_FK 
 FOREIGN KEY (AJV) 
 REFERENCES ASKARI.VOUCHER (VOUCHER_SEQ);

ALTER TABLE ASKARI.SAL_CONT_DETAIL
 ADD CONSTRAINT SAL_CONT_DET_ACV_FK 
 FOREIGN KEY (ACV) 
 REFERENCES ASKARI.VOUCHER (VOUCHER_SEQ);

