ALTER TABLE ORACLE.SC
 ADD (COLOR_ID  VARCHAR2(30));

ALTER TABLE ORACLE.SC DROP COLUMN BOXLOCK_SIZE;

ALTER TABLE ORACLE.SC DROP COLUMN TIP_SIZE;

ALTER TABLE ORACLE.SC DROP COLUMN OVER_ALL_LENGTH;

ALTER TABLE ORACLE.SC DROP COLUMN POINT_SIZE;

ALTER TABLE ORACLE.SC DROP COLUMN JAW_TYPE;

ALTER TABLE ORACLE.SC DROP COLUMN JAW_LENGTH;

ALTER TABLE ORACLE.SC DROP COLUMN BLADE_TYPE;

ALTER TABLE ORACLE.SC DROP COLUMN BLADE_LENGTH;

ALTER TABLE ORACLE.SC DROP COLUMN OPENING_QTY;

ALTER TABLE ORACLE.SC DROP COLUMN OPENING_VALUE;

ALTER TABLE ORACLE.SC DROP COLUMN GUAGE_AVAILABLE;

ALTER TABLE ORACLE.SC DROP COLUMN CENTER_PUNCH_SIZE;

ALTER TABLE ORACLE.SC DROP COLUMN DRILL_SIZE;

ALTER TABLE ORACLE.SC DROP COLUMN SCREW_ID;

ALTER TABLE ORACLE.SC DROP COLUMN SERRATED;

ALTER TABLE ORACLE.SC DROP COLUMN INSERT_BY;

ALTER TABLE ORACLE.SC DROP COLUMN INSERT_DATE;

ALTER TABLE ORACLE.SC DROP COLUMN INSERT_TERM;

ALTER TABLE ORACLE.SC DROP COLUMN LAST_UPDATED_BY;

ALTER TABLE ORACLE.SC DROP COLUMN LAST_UPDATED_DATE;

ALTER TABLE ORACLE.SC DROP COLUMN LAST_UPDATED_TERM;

ALTER TABLE ORACLE.SC DROP COLUMN MDL_NO;

ALTER TABLE ORACLE.SC DROP COLUMN FDA_PROD_CODE;

