ALTER TABLE ENIKA.INV_ROGP_BILL
 DROP PRIMARY KEY CASCADE;
DROP TABLE ENIKA.INV_ROGP_BILL CASCADE CONSTRAINTS;

CREATE TABLE ENIKA.INV_ROGP_BILL
(
  BILL_ID      NUMBER,
  BILL_DATE    DATE                             NOT NULL,
  STATUS       VARCHAR2(10 BYTE)                NOT NULL,
  SUPPLIER_ID  NUMBER                           NOT NULL,
  USER_ID      VARCHAR2(20 BYTE)                NOT NULL,
  FDATETIME    DATE                             NOT NULL,
  VOUCHER_SEQ  NUMBER
)
TABLESPACE SYSAUX
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ENIKA.INV_ROGP_BILL_PK ON ENIKA.INV_ROGP_BILL
(BILL_ID)
LOGGING
TABLESPACE SYSAUX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ENIKA.INV_ROGP_BILL ADD (
  CONSTRAINT INV_ROGP_BILL_PK
 PRIMARY KEY
 (BILL_ID));
------------------------------------------------
ALTER TABLE ENIKA.INV_ROGP_BILL_DET
 DROP PRIMARY KEY CASCADE;
DROP TABLE ENIKA.INV_ROGP_BILL_DET CASCADE CONSTRAINTS;

CREATE TABLE ENIKA.INV_ROGP_BILL_DET
(
  BILL_ID        NUMBER,
  IGP_DETAIL_ID  NUMBER
)
TABLESPACE SYSAUX
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ENIKA.INV_ROGP_BILL_DET_PK ON ENIKA.INV_ROGP_BILL_DET
(IGP_DETAIL_ID)
LOGGING
TABLESPACE SYSAUX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ENIKA.INV_ROGP_BILL_DET ADD (
  CONSTRAINT INV_ROGP_BILL_DET_PK
 PRIMARY KEY
 (IGP_DETAIL_ID));

ALTER TABLE ENIKA.INV_ROGP_BILL_DET ADD (
  CONSTRAINT INV_ROGP_BILL_DET_FK 
 FOREIGN KEY (BILL_ID) 
 REFERENCES ENIKA.INV_ROGP_BILL (BILL_ID));
