INSERT INTO SAL_CONT_MO_DETAIL
SELECT '24-MAR-2018', employee_id, our_cpo, cpo_year, 
OPERATION_RATE,    rec_qty, style, color_id, rsize, '', jcd_id FROM JCD_VIEW
WHERE PAYMENT_STATUS_ID='RELEASE' AND LOT_ID||'-'||LOT_SUB_ID IN 
(SELECT LOT_ID||'-'||LOT_SUB_ID FROM JCD J, SAL_CONT_MO_DETAIL S
WHERE S.JCD_ID=J.JCD_ID AND SAL_CONT_ID='24-MAR-2018')
AND OPERATION_RATE IS NOT NULL
ORDER BY STAGE, OPERATION_NO;

UPDATE JCD SET PAYMENT_STATUS_ID='POST' 
WHERE PAYMENT_STATUS_ID='RELEASE' AND LOT_ID||'-'||LOT_SUB_ID IN 
(SELECT LOT_ID||'-'||LOT_SUB_ID FROM JCD J, SAL_CONT_MO_DETAIL S
WHERE S.JCD_ID=J.JCD_ID AND SAL_CONT_ID='24-MAR-2018');

