CREATE USER &usr IDENTIFIED BY "one"  DEFAULT TABLESPACE "ORACUBES"  QUOTA UNLIMITED ON "ORACUBES";
GRANT "DBA" TO &usr WITH ADMIN OPTION;
ALTER USER &usr DEFAULT ROLE "DBA";

drop user cmi1 cascade;