ALTER TABLE GILLANI.EXP_CUSTOMER_STYLE_COLOR
 DROP PRIMARY KEY CASCADE;
DROP TABLE GILLANI.EXP_CUSTOMER_STYLE_COLOR CASCADE CONSTRAINTS;

CREATE TABLE GILLANI.EXP_CUSTOMER_STYLE_COLOR
(
  STYLE         VARCHAR2(50 BYTE)               NOT NULL,
  COLOR_ID      VARCHAR2(50 BYTE)               NOT NULL,
  SPECIAL_INST  VARCHAR2(200 BYTE),
  CUSTOMER_ID   NUMBER                          NOT NULL,
  CSC_ID        NUMBER
)
TABLESPACE ORACUBES
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX GILLANI.EXP_CUSTOMER_STYLE_COLOR_PK ON GILLANI.EXP_CUSTOMER_STYLE_COLOR
(CSC_ID)
LOGGING
TABLESPACE ORACUBES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX GILLANI.EXP_CUSTOMER_STYLE_COLOR_UK ON GILLANI.EXP_CUSTOMER_STYLE_COLOR
(CUSTOMER_ID, STYLE, COLOR_ID)
LOGGING
TABLESPACE ORACUBES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE GILLANI.EXP_CUSTOMER_STYLE_COLOR ADD (
  CONSTRAINT EXP_CUSTOMER_STYLE_COLOR_PK
 PRIMARY KEY
 (CSC_ID)
    USING INDEX 
    TABLESPACE ORACUBES
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ),
  CONSTRAINT EXP_CUSTOMER_STYLE_COLOR_UK
 UNIQUE (CUSTOMER_ID, STYLE, COLOR_ID)
    USING INDEX 
    TABLESPACE ORACUBES
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE GILLANI.EXP_CUSTOMER_STYLE_COLOR ADD (
  CONSTRAINT EXP_CUST_STYLE_CLR_FK 
 FOREIGN KEY (CUSTOMER_ID) 
 REFERENCES GILLANI.EXP_CUSTOMER (CUSTOMER_ID),
  CONSTRAINT EXP_CUST_STYLE_CLR_CLR_FK 
 FOREIGN KEY (COLOR_ID) 
 REFERENCES GILLANI.EXP_COLOR (COLOR_ID));
 --------------------------------------------------------------------------------
 ALTER TABLE GILLANI.EXP_CUSTOMER_STYLE_COLOR_PHOTO
 DROP PRIMARY KEY CASCADE;
DROP TABLE GILLANI.EXP_CUSTOMER_STYLE_COLOR_PHOTO CASCADE CONSTRAINTS;

CREATE TABLE GILLANI.EXP_CUSTOMER_STYLE_COLOR_PHOTO
(
  CSC_ID  NUMBER,
  PHOTO   LONG RAW
)
TABLESPACE ORACUBES
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX GILLANI.EXP_CUSTOMER_STYLE_COLOR_PH_PK ON GILLANI.EXP_CUSTOMER_STYLE_COLOR_PHOTO
(CSC_ID)
LOGGING
TABLESPACE ORACUBES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE GILLANI.EXP_CUSTOMER_STYLE_COLOR_PHOTO ADD (
  CONSTRAINT EXP_CUSTOMER_STYLE_COLOR_PH_PK
 PRIMARY KEY
 (CSC_ID)
    USING INDEX 
    TABLESPACE ORACUBES
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE GILLANI.EXP_CUSTOMER_STYLE_COLOR_PHOTO ADD (
  CONSTRAINT EXP_CUST_STYLE_CLR_PH_FK 
 FOREIGN KEY (CSC_ID) 
 REFERENCES GILLANI.EXP_CUSTOMER_STYLE_COLOR (CSC_ID));
  -------------------------------------------------------------------------------
  ALTER TABLE GILLANI.EXP_CPO_DETAIL
 ADD (CSC_ID  NUMBER);

ALTER TABLE GILLANI.EXP_CPO_DETAIL
 ADD CONSTRAINT EXP_CPO_DET_CSC_FK 
 FOREIGN KEY (CSC_ID) 
 REFERENCES GILLANI.EXP_CUSTOMER_STYLE_COLOR (CSC_ID);
 ------------------------------------