DROP TABLE GILLANI.HR_RAW_ATTENDANCE CASCADE CONSTRAINTS;

CREATE TABLE GILLANI.HR_RAW_ATTENDANCE
(
  LINE             VARCHAR2(300 BYTE),
  STATUS           VARCHAR2(20 BYTE),
  FDATETIME        DATE,
  ATTENDANCE_DATE  DATE
)
TABLESPACE ORACUBES
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


