ALTER TABLE GILLANI.HR_SETUP
 DROP PRIMARY KEY CASCADE;
DROP TABLE GILLANI.HR_SETUP CASCADE CONSTRAINTS;

CREATE TABLE GILLANI.HR_SETUP
(
  OT1_TIME_IN    NUMBER(4,2),
  OT2_TIME_OUT   NUMBER(4,2),
  SALARY_MONTH   DATE,
  EOBI_LIMIT     NUMBER(10),
  SS_LIMIT       NUMBER(10),
  EOBI_PER       NUMBER(10),
  SS_PER         NUMBER(10),
  EOBI_EMP_PER   NUMBER(10),
  OUT_TIME       NUMBER(4,2),
  IN_TIME        NUMBER(4,2),
  HR_SETUP_ID    NUMBER(1),
  BREAK          NUMBER,
  OT_LIMIT       NUMBER(5,2),
  PROVIDENT_PER  NUMBER,
  LATE_LIMIT     NUMBER
)
TABLESPACE ORACUBES
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX GILLANI.HR_SETUP_PK ON GILLANI.HR_SETUP
(HR_SETUP_ID)
LOGGING
TABLESPACE ORACUBES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE GILLANI.HR_SETUP ADD (
  CONSTRAINT HR_SETUP_PK
 PRIMARY KEY
 (HR_SETUP_ID)
    USING INDEX 
    TABLESPACE ORACUBES
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

