ALTER TABLE JILLANI.HR_MONTHLY_ATTENDANCE  ADD (DEDUCTION_REMARKS  VARCHAR2(200));
ALTER TABLE JILLANI.HR_MONTHLY_ATTENDANCE  ADD (OTHER_DEDUCTION  VARCHAR2(200));
ALTER TABLE JILLANI.HR_MONTHLY_ATTENDANCE  ADD (EARNING_REMARKS  VARCHAR2(200));
ALTER TABLE JILLANI.HR_MONTHLY_ATTENDANCE  ADD (LATE_HOURS  VARCHAR2(200));

ALTER TABLE JILLANI.HR_SALARY_ADVANCE DROP COLUMN COA_MAIN_ID;
ALTER TABLE JILLANI.HR_SALARY_ADVANCE DROP COLUMN COA_SUB_ID;
ALTER TABLE JILLANI.HR_SALARY_ADVANCE DROP COLUMN COA_ID;
