SELECT QUANTITY,  PROD_QTY  FROM EXP_CPO_DETAIL WHERE QUANTITY <> PROD_QTY;
UPDATE EXP_CPO_DETAIL SET PROD_QTY = QUANTITY;

SELECT JCD_ID, QTY, REC_QTY FROM PROD_JCD WHERE QTY <> REC_QTY;

SELECT J.OUR_CPO, J.POSITION,  J.OPERATION_ID, J.OPERATION_NO, V.QUANTITY, SUM(QTY) ISSUE, SUM(REC_QTY) REC FROM PROD_JCD J, EXP_CPO_DETAIL_VIEW V
WHERE J.OUR_CPO = V.OUR_CPO AND J.CPO_YEAR = V.CPO_YEAR AND J.POSITION = V.POSITION
GROUP BY J.OUR_CPO, J.CPO_YEAR, J.POSITION, V.QUANTITY, J.OPERATION_ID, J.OPERATION_NO
HAVING V.QUANTITY < SUM(QTY)  OR V.QUANTITY < SUM(REC_QTY) OR SUM(QTY) < SUM(REC_QTY)
ORDER BY OUR_CPO, POSITION;

SELECT J.OPERATION_ID, J.OPERATION_NO, SUM(QTY) ISSUE, SUM(REC_QTY) REC FROM PROD_JCD J
GROUP BY J.OUR_CPO, J.CPO_YEAR, J.POSITION, J.OPERATION_ID, J.OPERATION_NO;
