CREATE TABLE CLASSIC1.BRANCH_CLASS_SEC
(
  BRANCH_ID   VARCHAR2(100 BYTE),
  SECTION_ID  VARCHAR2(40 BYTE),
  USER_ID     VARCHAR2(20 BYTE)                 NOT NULL,
  FDATETIME   DATE                              NOT NULL,
  STATUS_ID   VARCHAR2(10 BYTE)                 NOT NULL,
  CLASS_ID    VARCHAR2(10 BYTE)                 NOT NULL,
  CONSTRAINT BRANCH_CLASS_SEC_STS_CHK   CHECK (status_id in ('HOLD','RELEASE')),
  CONSTRAINT BRANCH_CLASS_SEC_PK        PRIMARY KEY (BRANCH_ID, CLASS_ID, SECTION_ID),
  CONSTRAINT BRANCH_CLASS_SEC_USER_FK   FOREIGN KEY (USER_ID) 
  REFERENCES CLASSIC1.USERS (USER_ID));
